FROM node:24.16-alpine AS base
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@11 --activate
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .

ENV NODE_ENV=development
EXPOSE 3000
CMD ["pnpm", "run", "start:dev"]